name: hafsvilla
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  get: 4.6.5
  flutter: 
    sdk: flutter
  get_storage: ^2.0.3
  google_fonts: ^4.0.3
  hexcolor: ^3.0.1
  http: ^0.13.5
  lottie: ^2.2.0